### ISSUE TITLE
Can't Build

### ISSUE THREAD

**Issue by fire-eggs** [OpenImageViewer/OpenImageViewer#18]
So many build / readme problems.

- requires GLEW, which was not mentioned
- the codecs "buildconfig.h" has been reworked, readme not updated
- git clone "OpenImageViewer", not "oiv"
- u8string - ambiguous symbol [possibly _requires_ FreeType?]
- undefined class std::experimental::filesystem::v1::path
- the command line is "msbuild oiv.sln", and the full path isn't required if you use the
  "developer command prompt for visual studio"

So far, but I'm giving up here.

**Comment by TheNicker** [comment]
Build process needs a complete makeover.

It should be fixed by moving completely to CMake, adding all the dependencies as git sub-modules and integrating a CI.
OpenGL Renderer is currently not functional and can be removed via a build config setting. Moreover I have an abstract rendering solution from other commercial products that I plan to integrate in future versions.

Though it's not a tremendous work, at the moment I can't find the time to make these changes.

**Comment by TheNicker** [comment]
Updated build instructions
Added Continuous integration.
