### ISSUE TITLE
Doesn't work on Windows 7 SP1

### ISSUE THREAD

**Issue by Faberman** [OpenImageViewer/OpenImageViewer#59]
Both the provided binary file and the successfully built CMake project failed to run. Error: `The program can't start because api-ms-win-shcore-scaling-l1-1-1.dll is missing from your computer. Try reinstalling the program to fix this problem.`

OS: Windows 7 SP1 64-bit
Built using Microsoft Visual Studio Community 2019

**UPD.** Shcore is not available on Windows 7, and Windows 8.1+ is required: https://docs.microsoft.com/en-us/windows/win32/api/shellscalingapi/nf-shellscalingapi-getdpiformonitor
You should probably update the requirements: https://github.com/OpenImageViewer/OpenImageViewer#requirements

**Comment by TheNicker** [comment]
Fixing getdpiformonitor won't be an issue.
I know that there are a few more calls to newer API but they shouldn't be many, and I can see that a significant  portion of users still use Windows 7.


VS2019 defaults its SDK to the newest possible. 
In order to review the required effort, the project should be compiled against the newest windows 7 SDK. the compilation errors will tell the story.
that may be a little tricky with VS2019, but AFAIK possible.

once it's done, we'll have a wider perspective whether Windows 7 support is worth maintaining

**Comment by TheNicker** [comment]
PR #60  should solve the issue.

The program should now run on windows 7 SP1, also on a hyper-v machine.
Make sure that the following windows updates are installed:
https://github.com/TheNicker/OpenImageViewerFork#when-using-windows-7-sp1-make-sure-the-following-are-installed

**Comment by TheNicker** [comment]
Fixed in 0.17
